# -*- coding: utf-8 -*-
"""TravelPlan 技能安装器 —— 把两个技能铺到任意宿主 agent 平台。

支持的范围
----------
**Windows 10/11 + 任意宿主 agent 平台。** 各平台的差异（技能目录约定、
入口文件、是否认 SKILL.md）都定义在 `xhs-humanized-collect/scripts/platform_compat.py`
的 `AGENT_TARGETS` 里，本脚本只负责执行安装。

| 宿主 | 技能目录 | 入口文件 |
|---|---|---|
| WorkBuddy / CodeBuddy | `~/.workbuddy/skills/` | 不需要（自动发现） |
| Claude Code | `~/.claude/skills/` | 项目 `CLAUDE.md` + `~/.claude/CLAUDE.md` + `AGENTS.md` |
| Codex CLI | `%LOCALAPPDATA%\\agent-skills\\skills\\` | 项目 `AGENTS.md` + `~/.codex/AGENTS.md` |
| Cursor | 同上 | 项目 `AGENTS.md` + `.cursor/rules/travelplan.mdc` |
| Gemini CLI | 同上 | 项目 `GEMINI.md` + `~/.gemini/GEMINI.md` |
| Windsurf | 同上 | 项目 `AGENTS.md` + `.windsurf/rules/travelplan.md` |
| 其它 | 同上 | 项目 `AGENTS.md`（跨工具事实标准） |

不认 SKILL.md 的平台，靠生成的入口文件获得一份**浓缩操作说明**；
更详细的规则仍在各技能的 `SKILL.md` / `references/` 里，入口文件只做索引。

用法
----
    python install.py --list                      # 看支持哪些宿主、本机装了哪些
    python install.py --target auto               # 装到本机检测到的全部宿主
    python install.py --target claude             # 只装某一个
    python install.py --target all                # 全都装
    python install.py --target cursor --project D:\\my-trip
    python install.py --target auto --dry-run     # 只打印将要做什么
    python install.py --target cursor --uninstall # 卸载（只删自己生成的入口文件）

安全
----
- 只往「技能根目录」和「入口文件」写，不碰其它任何位置。
- 生成的入口文件带 `generated by TravelPlan install.py` 标记；
  `--uninstall` **只删带这个标记的文件**，不会误删你自己写的规则文件。
- 不覆盖已存在的技能目录，除非加 `--force`（避免把用户改过的版本冲掉）。
"""
import argparse
import os
import shutil
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_NAMES = ("travel-guide-builder", "xhs-humanized-collect")
MARK = "<!-- generated by TravelPlan install.py -->"
MARK_MDC = "generated by TravelPlan install.py"


def _load_compat():
    """从仓库里的技能目录加载兼容层（不用装就能跑）。"""
    cands = [os.path.join(HERE, "xhs-humanized-collect", "scripts")]
    for c in cands:
        if os.path.isfile(os.path.join(c, "platform_compat.py")):
            if c not in sys.path:
                sys.path.insert(0, c)
            import platform_compat
            return platform_compat
    raise SystemExit(
        "找不到 xhs-humanized-collect/scripts/platform_compat.py。\n"
        "本脚本必须在 TravelPlan 仓库根目录运行（与两个技能目录同级）。")


PC = _load_compat()
PC.setup_stdout()


# ============================================================ 入口文件内容

def _entry_body(target_key, skills_root):
    """生成浓缩操作说明（各平台共用正文，标题/前言按平台微调）。"""
    py = PC.python_exe()
    chrome = PC.find_chrome() or "（未检测到，请装 Chrome）"
    tgb = os.path.join(skills_root, "travel-guide-builder")
    xhs = os.path.join(skills_root, "xhs-humanized-collect")
    return """{MARK}
# TravelPlan —— 旅游攻略 xlsx + 图文路书（技能集）

> 由 TravelPlan 安装器生成于 {DATE}，宿主平台：**{LABEL}**。
> 本文件是**入口索引**；权威说明在：
> - `{TGB}\\SKILL.md`
> - `{XHS}\\SKILL.md`
> - `{TGB}\\references\\scraping-playbook.md`（各平台抓取的实操与坑）

## 一、这两个技能是什么

| 技能 | 作用 |
|---|---|
| `travel-guide-builder` | 按用户**自有的表格模板**生成多 sheet 行程攻略 xlsx（全部行程 / 人均预算 / 费用明细 / 物品清单 / 景点地图），再出**图文路书 HTML** 与 **PPT** |
| `xhs-humanized-collect` | 拟人化浏览器采集（小红书、携程酒店、神州租车等）：持久登录态 + 常驻会话 + 反风控节奏 |

安装位置：`{SKILLS_ROOT}`

## 二、环境要求（Windows）

- Python 3.10+（本机解释器：`{PY}`）
- 依赖：`py -3 -m pip install openpyxl python-pptx playwright pillow jinja2`
- 浏览器：需要**原生 Chrome**（本机检测到：`{CHROME}`）；
  `playwright install chromium` 只用于截图/渲染，**抓取不能用它**
  （携程 / 神州的指纹风控会直接拦，页面只显示 `whaleguard block`）

## 三、标准工作流

```bat
rem ① 组装内容 → 生成 xlsx
py -3 "{TGB}\\scripts\\build_guide_xlsx.py" content.json "旅程攻略.xlsx"

rem ② 抽内容 → 生成图文路书 HTML（先 --stage 1 出封面+总篇章+DAY1 让用户确认）
py -3 "{TGB}\\scripts\\roadbook_extract_content.py"
py -3 "{TGB}\\scripts\\roadbook_build_html.py" --stage 1

rem ③ 截图验收（分段截图，目视检查排版）
py -3 "{TGB}\\scripts\\html_screenshot.py" "路书.html" 6

rem ④ PPT（两套：详细版 / 简洁版）
py -3 "{TGB}\\scripts\\extract_xlsx_slides.py"
py -3 "{TGB}\\scripts\\build_ppt_detail.py" --stage 1
```

## 四、硬约束（用户明确定过，**不要自行改**）

1. **PDF 一律不自动生成。** 交付只给 HTML + 「另存为 PDF」的打印步骤
   （A4 / 纵向 / 每版 1 页 / 边距缩放默认 / ☑ 页眉和页脚 / **☑ 背景图形**）。
   不要临时写一个 HTML→PDF 脚本出来。
2. **地图四级优先级**（按信息价值，不是画质）：
   ① 小红书搜到的大景点导览图（**必须先甄别**：图上有可读地名 / 帖文语境确实指向该景点 /
   相对位置合常识 / 非多景点拼贴；任一项不过就降级，**配错景点的地图比没有更糟**）
   → ② 天地图 → ③ 高德 Web 服务静态地图（需用户自备 key，走 `AMAP_WEB_KEY` 环境变量）
   → ④ 其它保底。每种都要在图注写明来源与审图号。
3. **所有平台抓取走常驻会话，登录一次。** 起一个有头浏览器 + CDP 端口，
   采集脚本 attach 上去，**结束只关标签页、绝不关浏览器**；
   登录态用 `human_act.save_cookies/restore_cookies` 落盘快照（含会话级 cookie）。
4. **只读价，绝不下单。** 走到「确认订单」页读全额为止，脚本内置禁区词表。
   撞到验证码/滑块立即中止并告知用户，不硬试。
5. **xlsx 冻结窗格**：`全部行程` = 首行 + A、B 列（`C2`）；`费用明细` = 只冻结首行（`A2`）；
   人均预算 / 物品清单 / 景点地图 = **不冻结**。
6. **富文本默认开启**（`put()` 的 `rich` 默认 `True`）：`【景点】` 红加粗、`〔交通〕/〔事项〕` 棕加粗。
   回读校验必须 `load_workbook(path, rich_text=True)`，否则会误判「没生效」。
7. **预算双口径**：出行区间若覆盖国家法定节假日，**必须**给「普通日 vs 节假日」双预算
   并标涨幅倍数；纯普通日给单价并注明「非节假日口径」。

## 五、跨平台通用的坑（都是实测踩出来的）

- **中文 Windows 的输出编码**：`tasklist` / `taskkill` 输出是 GBK。
  用 `subprocess(..., text=True)` 会在 reader 线程抛 `UnicodeDecodeError`，
  被吞掉后表现为「进程活着却判断成已死」→ 一律按字节读、再自行解码。
- **写给用户双击的 `.bat` 必须纯 ASCII + CRLF**：`cmd.exe` 按 GBK 解析 UTF-8 会满屏乱码，
  `chcp 65001` 也救不回来（它在 chcp 生效前就解析完了）。
  更稳的做法是直接给「Win+R 一行命令」。
- **`innerText` 会漏掉 `content-visibility` 折叠区的内容** → 按文本找元素找不到，
  要用遍历文本节点的方式（见 `human_act.deep_text`）。
- **按钮文字可能含空格**（前端用空格做字间距），如「确 认」→ 匹配前先归一化空白。
- **不要用逗号把多个选择器拼成一个**：那是并集，`.first` 按 DOM 顺序取，容易点错元素。
- **抓不到 ≠ 站点不做网页版**：先确认是否缺登录态 / 定位授权 / 前置交互。

## 六、怎么让 agent 开始干活

直接对 agent 说，例如：

> 用 travel-guide-builder 技能，按我给的模板生成【青海甘肃大环线】【9 天 8 晚】【自驾】攻略，
> 旅行时间 2027/7/17-7/25，8 人（4 男 4 女），深圳出发，飞机往返兰州。
> **先生成 xlsx，其它文件先不生成。**

约定：**先小步交付让用户确认版式，再全量**（路书先 `--stage 1`，PPT 同理）。
"""


def _wrap(target_key, body):
    """按目标平台包装（Cursor 的 .mdc 需要 YAML frontmatter）。"""
    if target_key == "cursor":
        fm = ("---\n"
              "description: TravelPlan —— 旅游攻略 xlsx + 图文路书技能集"
              "（生成行程攻略表格、图文路书 HTML、PPT；含小红书/携程/神州采集）\n"
              "globs:\n"
              "alwaysApply: false\n"
              "---\n\n")
        # .mdc 里不放 HTML 注释标记，改用一个可见的说明行
        return fm + body.replace(MARK, "<!-- %s -->" % MARK_MDC)
    return body


# ============================================================ 安装动作

def _skills_src():
    src = {}
    for n in SKILL_NAMES:
        p = os.path.join(HERE, n)
        if not os.path.isdir(p):
            raise SystemExit("仓库里找不到技能目录：%s" % p)
        src[n] = p
    return src


def _copy_skill(src, dst, force=False, dry=False):
    """把技能目录复制过去。返回 'ok' / 'skip' / 'update'。"""
    if os.path.isdir(dst):
        if not force:
            return "skip"
        if not dry:
            shutil.rmtree(dst)
    if not dry:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns(
            "__pycache__", "*.pyc", ".git"))
    return "ok" if not force else "update"


def _write_entry(path, content, dry=False):
    if os.path.exists(path):
        try:
            old = open(path, encoding="utf-8").read()
        except Exception:
            old = ""
        if MARK not in old and MARK_MDC not in old:
            return "occupied"          # 用户自己写的文件，绝不覆盖
    if not dry:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
    return "ok"


def install_one(key, project, force=False, dry=False, entry=True):
    t = PC.agent_target(key)
    src = _skills_src()
    roots = PC.skills_roots_for(key)
    root = roots[0]

    print()
    print("── %s（%s）" % (t["label"], key))
    print("   技能根目录 : %s" % root)
    if t["reads_skill_md"]:
        print("   识别方式   : 直接读 SKILL.md（无需入口文件）")
    else:
        print("   识别方式   : 入口文件 → 技能目录 %s" % root)
    if t["note"]:
        print("   备注       : %s" % t["note"])

    ok = True
    for n in SKILL_NAMES:
        r = _copy_skill(src[n], os.path.join(root, n), force=force, dry=dry)
        label = {"ok": "将安装" if dry else "已安装",
                 "skip": "已存在（跳过；--force 可覆盖）",
                 "update": "将覆盖更新" if dry else "已覆盖更新"}[r]
        print("   %-22s %s" % (n, label))

    if not entry:
        return ok
    body = _wrap(key, _entry_body(key, root).format(
        MARK=MARK, DATE=time.strftime("%Y-%m-%d"), LABEL=t["label"],
        SKILLS_ROOT=root, TGB=os.path.join(root, "travel-guide-builder"),
        XHS=os.path.join(root, "xhs-humanized-collect"),
        PY=PC.python_exe(), CHROME=PC.find_chrome() or "（未检测到）"))
    for path in PC.entry_files_for(key, project=project):
        r = _write_entry(path, body + "\n", dry=dry)
        label = {"ok": "写入", "occupied": "已存在且非本工具生成 → 跳过（不覆盖你的文件）"}[r]
        print("   入口 %-46s %s" % (_short(path), label))
        if r == "occupied":
            ok = False
    return ok


def uninstall_one(key, project, dry=False):
    t = PC.agent_target(key)
    roots = PC.skills_roots_for(key)
    root = roots[0]
    print()
    print("── 卸载 %s（%s）" % (t["label"], key))
    for n in SKILL_NAMES:
        d = os.path.join(root, n)
        if os.path.isdir(d):
            if not dry:
                shutil.rmtree(d, ignore_errors=True)
            print("   删除技能目录 %s" % _short(d))
        else:
            print("   技能目录不存在，跳过 %s" % _short(d))
    for path in PC.entry_files_for(key, project=project):
        if not os.path.exists(path):
            continue
        try:
            txt = open(path, encoding="utf-8").read()
        except Exception:
            continue
        if MARK in txt or MARK_MDC in txt:
            if not dry:
                os.remove(path)
            print("   删除入口文件 %s" % _short(path))
        else:
            print("   保留（非本工具生成）%s" % _short(path))


def _short(p):
    """把 home 前缀缩成 ~，过长则截尾。两种分隔符都要认。"""
    home = os.path.normpath(os.path.expanduser("~"))
    q = os.path.normpath(p)
    if os.path.normcase(q).startswith(os.path.normcase(home)):
        q = "~" + q[len(home):]
    return q if len(q) < 62 else "…" + q[-59:]


def cmd_list():
    print("=" * 78)
    print("支持的宿主 agent 平台")
    print("=" * 78)
    print("  %-11s %-24s %-30s %s" % ("key", "平台", "技能根目录", "识别方式"))
    print("  " + "-" * 74)
    for key in PC.AGENT_TARGETS:
        t = PC.AGENT_TARGETS[key]
        root = PC.skills_roots_for(key)[0]
        root = "…\\" + "\\".join(root.replace("/", "\\").split("\\")[-2:])
        print("  %-11s %-24s %-30s %s"
              % (key, t["label"], root,
                 "SKILL.md" if t["reads_skill_md"] else "入口文件"))
    print()
    print("=" * 78)
    print("本机检测到的宿主")
    print("=" * 78)
    found = PC.detect_agents()
    for key, label, p in found:
        print("  ✔ %-11s %-24s %s" % (key, label, p))
    if not found:
        print("  （未检测到；用 --target 显式指定）")
    print()
    print("  解释器：%s" % PC.python_exe())
    print("  浏览器：%s" % (PC.find_chrome() or "（未检测到原生 Chrome）"))
    print()
    print("  提示：`--target auto` 会装到上面检测到的全部宿主。")
    return 0


def main():
    ap = argparse.ArgumentParser(
        description="把 TravelPlan 技能安装到各种 agent 平台（Windows）")
    ap.add_argument("--target", default="",
                    help="auto | all | %s" % " | ".join(PC.AGENT_TARGETS))
    ap.add_argument("--project", default=os.getcwd(),
                    help="项目级入口文件写到哪（默认当前目录）")
    ap.add_argument("--force", action="store_true", help="覆盖已存在的技能目录")
    ap.add_argument("--no-entry", action="store_true", help="只装技能，不生成入口文件")
    ap.add_argument("--uninstall", action="store_true", help="卸载")
    ap.add_argument("--dry-run", action="store_true", help="只打印将要做什么")
    ap.add_argument("--list", action="store_true", help="列出支持的宿主与本机检测结果")
    args = ap.parse_args()

    if args.list or not args.target:
        return cmd_list()

    keys = []
    if args.target == "all":
        keys = list(PC.AGENT_TARGETS)
    elif args.target == "auto":
        keys = [k for k, _, _ in PC.detect_agents()]
        if not keys:
            print("没检测到任何已知宿主。请用 --target 显式指定，例如 --target claude")
            return 1
    elif args.target in PC.AGENT_TARGETS:
        keys = [args.target]
    else:
        print("未知目标：%s\n可选：auto / all / %s"
              % (args.target, " / ".join(PC.AGENT_TARGETS)))
        return 1

    print("=" * 78)
    print("%s%s" % ("[演练] " if args.dry_run else "",
                    "卸载" if args.uninstall else "安装"))
    print("  仓库根目录 : %s" % HERE)
    print("  项目目录   : %s" % args.project)
    print("  目标       : %s" % "、".join(keys))
    print("=" * 78)

    # 提醒：项目目录若在仓库内，生成的入口文件会带本机路径，别提交
    rp = os.path.abspath(args.project).lower()
    if rp.startswith(HERE.lower()):
        print()
        print("⚠️ --project 指到了仓库内部。生成的入口文件会包含本机绝对路径，")
        print("   提交前请把它加进 .gitignore，或改用仓库外的项目目录。")

    bad = []
    for k in keys:
        if args.uninstall:
            uninstall_one(k, args.project, dry=args.dry_run)
        elif not install_one(k, args.project, force=args.force,
                             dry=args.dry_run, entry=not args.no_entry):
            bad.append(k)

    print()
    print("=" * 78)
    if args.dry_run:
        print("演练结束（未改动任何文件）。去掉 --dry-run 即真正执行。")
    elif bad:
        print("完成，但有需要人工处理的项：%s" % "、".join(bad))
        print("（通常是入口文件已存在且不是本工具生成的 —— 我们不会覆盖你的文件，")
        print("  请自行把其中的规则合并进去，或删掉它后重跑。）")
    else:
        print("完成。重开一次 agent 会话让它加载新的技能/入口文件。")
        print()
        print("验证：")
        print("  py -3 -c \"import sys;print(sys.version)\"")
        print("  py -3 \"%s\" --selfcheck" % os.path.join(
            PC.skills_roots_for(keys[0])[0], "xhs-humanized-collect",
            "scripts", "platform_compat.py"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
